<?php

// Include the PhpSpreadsheet classes

// Simple Cache
require_once "SimpleCache/CacheInterface.php";

// php-enum
require_once "php-enum/Enum.php";

// ZipStream
require_once "ZipStream/Bigint.php";
require_once "ZipStream/File.php";
require_once "ZipStream/ZipStream.php";
// Option
require_once "ZipStream/Option/Archive.php";
require_once "ZipStream/Option/File.php";
require_once "ZipStream/Option/Method.php";
require_once "ZipStream/Option/Version.php";

// PHP Spreadsheet
// Root
require_once "PhpOffice/PhpSpreadsheet/HashTable.php";
require_once "PhpOffice/PhpSpreadsheet/IComparable.php";
require_once "PhpOffice/PhpSpreadsheet/IOFactory.php";
require_once "PhpOffice/PhpSpreadsheet/ReferenceHelper.php";
require_once "PhpOffice/PhpSpreadsheet/Settings.php";
// Cell
require_once "PhpOffice/PhpSpreadsheet/Cell/Coordinate.php";
require_once "PhpOffice/PhpSpreadsheet/Cell/Cell.php";
require_once "PhpOffice/PhpSpreadsheet/Cell/DataType.php";
require_once "PhpOffice/PhpSpreadsheet/Cell/IValueBinder.php";
require_once "PhpOffice/PhpSpreadsheet/Cell/DefaultValueBinder.php";
// Chart
require_once "PhpOffice/PhpSpreadsheet/Chart/DataSeries.php";
// Colleciton
require_once "PhpOffice/PhpSpreadsheet/Collection/CellsFactory.php";
require_once "PhpOffice/PhpSpreadsheet/Collection/Cells.php";
require_once "PhpOffice/PhpSpreadsheet/Collection/Memory/SimpleCache1.php";
// Calculation
require_once "PhpOffice/PhpSpreadsheet/Calculation/Calculation.php";
require_once "PhpOffice/PhpSpreadsheet/Calculation/Category.php";
require_once "PhpOffice/PhpSpreadsheet/Calculation/Engine/BranchPruner.php";
require_once "PhpOffice/PhpSpreadsheet/Calculation/Engine/CyclicReferenceStack.php";
require_once "PhpOffice/PhpSpreadsheet/Calculation/Engine/Logger.php";
require_once "PhpOffice/PhpSpreadsheet/Calculation/Functions.php";
// Document
require_once "PhpOffice/PhpSpreadsheet/Document/Properties.php";
require_once "PhpOffice/PhpSpreadsheet/Document/Security.php";
// Reader
require_once "PhpOffice/PhpSpreadsheet/Reader/Security/XmlScanner.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/IReadFilter.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/DefaultReadFilter.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/IReader.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/BaseReader.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/BaseParserClass.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/AutoFilter.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/PageSetup.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/Namespaces.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/Hyperlinks.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/WorkbookView.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/Theme.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/Properties.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/ColumnAndRowAttributes.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/SheetViewOptions.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/SheetViews.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx/Styles.php";
require_once "PhpOffice/PhpSpreadsheet/Reader/Xlsx.php";
// Style
require_once "PhpOffice/PhpSpreadsheet/Style/Supervisor.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Font.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Color.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Fill.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Borders.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Border.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Alignment.php";
require_once "PhpOffice/PhpSpreadsheet/Style/NumberFormat.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Protection.php";
require_once "PhpOffice/PhpSpreadsheet/Style/Style.php";
// Worksheet
require_once "PhpOffice/PhpSpreadsheet/Worksheet/AutoFilter/Column/Rule.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/AutoFilter.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/Dimension.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/ColumnDimension.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/PageSetup.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/PageMargins.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/HeaderFooter.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/RowDimension.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/SheetView.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/Protection.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/Iterator.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/Worksheet.php";
require_once "PhpOffice/PhpSpreadsheet/Worksheet/Validations.php";
// Writer
require_once "PhpOffice/PhpSpreadsheet/Writer/IWriter.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/BaseWriter.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/WriterPart.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Chart.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Comments.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/ContentTypes.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/DocProps.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Drawing.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Rels.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/RelsRibbon.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/RelsVBA.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/StringTable.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Style.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Theme.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Table.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/DefinedNames.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/AutoFilter.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Workbook.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx/Worksheet.php";
require_once "PhpOffice/PhpSpreadsheet/Writer/Xlsx.php";
// Shared
require_once "PhpOffice/PhpSpreadsheet/Shared/Date.php";
require_once "PhpOffice/PhpSpreadsheet/Shared/File.php";
require_once "PhpOffice/PhpSpreadsheet/Shared/IntOrFloat.php";
require_once "PhpOffice/PhpSpreadsheet/Shared/StringHelper.php";
require_once "PhpOffice/PhpSpreadsheet/Shared/XMLWriter.php";
// Root 2nd part
require_once "PhpOffice/PhpSpreadsheet/Spreadsheet.php";
